services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - h2-data:/app/data

volumes:
  h2-data:
