CREATE TABLE shortened_urls (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code      VARCHAR(4) UNIQUE,
    original_url    varchar(2048) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP NULL
)
